### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by hissssst** [ihumanable/patch#71]
Hi, I've created a library called [Repatch](https://github.com/hissssst/repatch) and I've borrowed some code for the recompiler module from this amazing library. I've included this MIT license in the license in Repatch, but I want to make sure that licensing is correct

**Comment by ihumanable** [comment]
I'm not a lawyer, but my understanding of the MIT license agrees with your use of it.  Happy you found the code useful and I'll have to check out repatch.

Also this isn't related to this issue, and perhaps you are using repatch now, but I think the latest release ended up fixing the issue you were experiencing here https://github.com/ihumanable/patch/pull/63 

Good luck with the new library and thank you for the mention in the README, I don't think that's required but it's definitely appreciated.  Happy coding :D
